### ISSUE TITLE
Managed Debugging Assistant 'PInvokeStackImbalance'

### ISSUE THREAD

**Issue by hamaluik** [andrecarlucci/openrealsense#1]
Trying to run this sample:

```csharp
using System;
using OpenRealSense;
using System.IO;

class Program
{
    static void Main(string[] args)
    {
        var context = Context.Create(11100);
        var device = context.GetDevice(0);

        device.EnableStream(StreamType.Depth, 640, 480, FormatType.Z16, 30);
        device.Start();

        while (true)
        {
            device.WaitForFrames();
            var frameInBytes = device.GetFrameData(StreamType.Depth).Bytes;
            using (var stream = new MemoryStream(frameInBytes))
            {
                using (var reader = new BinaryReader(stream))
                {
                    //do something with the frame :)
                }
            }
        }
    }
}
```

I get an exception on `Context.create(11100)`:

> **Managed Debugging Assistant 'PInvokeStackImbalance'** : 'A call to PInvoke function 'OpenRealSense!OpenRealSense.NativeMethods.Context::rs_create_context' has unbalanced the stack. This is likely because the managed PInvoke signature does not match the unmanaged target signature. Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature.'

Using version 1.12.0 from NuGet and .NET 4.6.2 console app.

Any idea what's going on and how to fix it?

Thanks!

**Comment by hamaluik** [comment]
I seem to have fixed it by changing all the DLL imports from:

```csharp
[DllImport(DllSource.Path)]
```

to:

```csharp
[DllImport(DllSource.Path, CallingConvention = CallingConvention.Cdecl)]
```

I'll confirm that this is indeed fixes everything then I'll make a pull request!

**Comment by andrecarlucci** [comment]
Hi @FuzzyWuzzie , Thanks a lot. Let me know if you need any help :)

**Comment by andrecarlucci** [comment]
Tks, @FuzzyWuzzie , the nuget package with your changes are already online :)
https://www.nuget.org/packages/OpenRealSense/

**Comment by hamaluik** [comment]
Awesome, thanks!
