### ISSUE TITLE
.NET Target FW

### ISSUE THREAD

**Issue by asm9809** [andrecarlucci/openrealsense#3]
Attempted NuGet install onto project with .NET 4.5 framework and was given " You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework" 

What FW is supported by openrealsense?

**Comment by andrecarlucci** [comment]
Hi @asm9809 ,

I'm using netstandard1.5:

https://github.com/dotnet/standard/blob/master/docs/versions/netstandard1.5.md

**Comment by asm9809** [comment]
thank you
